#! /bin/bash

./plots.py -l \
              configs/np_factors_calc_yb*.json \
              configs/pdf_uncert_comp.py \
              configs/scale_uncert_comp.py \
              configs/nlo_xs_comp.py \
              configs/kfactor_comp.py \
              configs/theo_unc_overview.py \
              configs/ratio_to_CT14nlo+np_totcomp.py \
              configs/ratio_to_MMHT2014nlo+np_totcomp.py \
              configs/ratio_to_NNPDF30nlo+np_totcomp.py \
              configs/ratio_to_NNPDF30nlo+np_varcomp.py \
              configs/trigger_eff.py \
              configs/jec_unc_split.py \
              configs/metoversumet.json \
              configs/jet_distributions.py \
              configs/jet_constituents.py \
              configs/jetideff_*.json \
              configs/genvsreco*.json \
              configs/rap_corr_data.py \
              configs/run_comparison.py \
              configs/npv_*.json \
              configs/dijet_distributions.py \
              configs/jet12_rapidity.py \
              configs/ratio_reco_to_data*.json \
              configs/gen_vs_reco_vs_gen_ptavg.py \
              configs/resolution_ptavg_crystalball.py \
              configs/resolution_yb0ys0_bin10.json \
              configs/resolution_yb0ys0_bin10_cb.json \
              configs/res_matrix_ptavg_normalized.py \
              configs/unf_nlo_check.py \
              configs/stat_unc_fractional.py \
              configs/unf_nlo_corr.py \
              configs/exp_unc_overview.py \
              configs/ptavg_spectrum.py \
              configs/pdf_comp_direct.py \
              configs/pdf_comp_split.py \
              configs/pdf_comp_overview.py \
